// menuBuilder
export const UPDATE_LOVED_ITEM = 'UPDATE_LOVE_ITEM';
export const GET_LOVED_ITEMS = 'GET_LOVED_ITEMS';
export const GET_LOVED_ITEMS_SUCCESS = 'GET_LOVED_ITEMS_SUCCESS';
export const GET_LOVED_ITEMS_FAIL = 'GET_LOVED_ITEMS_FAIL'

// cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART_PRICE = 'UPDATE_CART_PRICE';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const INCREASE_NUMBER_OF_ITEM_IN_CART = 'INCREASE_NUMBER_OF_ITEM_IN_CART';
export const DECREASE_NUMBER_OF_ITEM_IN_CART = 'DECREASE_NUMBER_OF_ITEM_IN_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';
export const COMBINE_LOCAL_STORE_CART_TO_DB_CART_SUCCESS = 'COMBINE_LOCAL_STORE_CART_TO_DB_CART_SUCCESS';
export const DELETE_CART_START = 'DELETE_CART_START';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAIL= 'DELETE_CART_FAIL';

// export const GET_CART_FROM_LOCAL_STORAGE_SUCCESS = 'GET_CART_FROM_LOCAL_STORAGE_SUCCESS';

// auth
export const IN_OR_UP = 'IN_OR_UP';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_RESET_ERROR = 'AUTH_RESET_ERROR';

// security
export const CHANGE_PW_START = 'CHANGE_PW_START';
export const CHANGE_PW_SUCCESS = 'CHANGE_PW_SUCCESS';
export const CHANGE_PW_FAIL = 'CHANGE_PW_FAIL';

export const SEND_PASSWORD_RESET_EMAIL_START = 'SEND_PASSWORD_RESET_EMAIL_START';
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = 'SEND_PASSWORD_RESET_EMAIL_SUCCESS';
export const SEND_PASSWORD_RESET_EMAIL_FAIL = 'SEND_PASSWORD_RESET_EMAIL_FAIL';

export const DELETE_ACCOUNT_START = 'DELETE_ACCOUNT_START';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';

// users
export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';

export const CREATE_USER = 'CREATE_USER';

export const CLEAN_USER_PROFILE = 'CLEAN_USER_PROFILE';

export const EDIT_DETAILS_USER_START = 'EDIT_DETAILS_USER_START';
export const EDIT_DETAILS_USER = 'EDIT_DETAILS_USER';
export const EDIT_DETAILS_USER_SUCCESS = 'EDIT_DETAILS_USER_SUCCESS';
export const EDIT_DETAILS_USER_FAIL = 'EDIT_DETAILS_USER_FAIL';

export const EDIT_ADDRESS_USER_START = 'EDIT_ADDRESS_USER_START';
export const EDIT_ADDRESS_USER = 'EDIT_ADDRESS_USER';
export const EDIT_ADDRESS_USER_SUCCESS = 'EDIT_ADDRESS_USER_SUCCESS';
export const EDIT_ADDRESS_USER_FAIL = 'EDIT_ADDRESS_USER_FAIL';

export const EDIT_CONTACT_USER_START = 'EDIT_CONTACT_USER_START';
export const EDIT_CONTACT_USER = 'EDIT_CONTACT_USER';
export const EDIT_CONTACT_USER_SUCCESS = 'EDIT_CONTACT_USER_SUCCESS';
export const EDIT_CONTACT_USER_FAIL = 'EDIT_CONTACT_USER_FAIL';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL= 'DELETE_USER_FAIL';